name: Node.js CI and NPM Publish

on:
    push:
        branches: [main]
    release:
        types: [created]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '16'
            - name: Install dependencies
              run: npm install
            - name: Run tests
              run: npm test

    publish-npm:
        needs: build
        if: github.event_name == 'release' && github.event.action == 'created'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node.js for publishing
              uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  registry-url: https://registry.npmjs.org/
            - name: Publish to npm
              run: npm publish --access=public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_SECRET}}
